### ISSUE TITLE
Format for print

### ISSUE THREAD

**Issue by nishantsoni4** [techlift-tech/erpnext_prime#10]
A-5 Print Profile for Payment & Journal Voucher (Urgent)

**Comment by nishantsoni4** [comment]
![WhatsApp Image 2019-11-21 at 6 02 53 PM](https://user-images.githubusercontent.com/26823124/69338559-7a4ad980-0c89-11ea-8759-760fa3f46a8a.jpeg)
 for "payment and receive" in A5 format

**Comment by nishantsoni4** [comment]
and yeh pos ke print ke liye bhi chahiye

**Comment by nishantsoni4** [comment]
iska pos format mey bhi dekh lena format for payment

**Comment by nishantsoni4** [comment]
Ismey POS format bhi chahiye

**Comment by surajTechlift** [comment]
done
