### ISSUE TITLE
Erp mail not send automatically we have already discuss

### ISSUE THREAD

**Issue by nishantsoni4** [techlift-tech/erpnext_prime#12]

**Comment by nishantsoni4** [comment]
@palashjhabak

**Comment by nishantsoni4** [comment]
sir ismey abhi 2 id bata rahi hai apne ko aisa chaiye ki jiski id open hai toh uska by default id lele

**Comment by palashjhabak** [comment]
haa wo koi issue nahi hai wo ho jayega, lekin ek baar pehle verify ye kar le ki apne aap jaa raha hai ki nahi fir wo wal akarta hu

**Comment by nishantsoni4** [comment]
haan test kiya mey chal raha hai abhi
