### ISSUE TITLE
In salary slip attendance not showing correctly

### ISSUE THREAD

**Issue by nishantsoni4** [techlift-tech/erpnext_prime#13]

**Comment by nishantsoni4** [comment]
@palashjhabak

**Comment by palashjhabak** [comment]
@nishantsoni4 Have fixed this. It wasnt an issue, but a setting in Salary Component. There is a check box called "Depends on Payment Days" if unchecked it wont get affected by attendance. It is their because we wouldnt want some components to  get affected by attendance
