### ISSUE TITLE
Show total Loyalty points in POS checkout page

### ISSUE THREAD

**Issue by palashjhabak** [techlift-tech/erpnext_prime#19]

**Comment by nishantsoni4** [comment]
![1583330633762](https://user-images.githubusercontent.com/26823124/75887297-985ed300-5e4f-11ea-882b-b57753e9325a.png)

**Comment by nishantsoni4** [comment]
sir yahan total nahi  araha hai

**Comment by palashjhabak** [comment]
arre abhi live me dala nahi hua aaj dalunga

**Comment by palashjhabak** [comment]
this is now live
