### ISSUE TITLE
Sales Invoice Format

### ISSUE THREAD

**Issue by nishantsoni4** [techlift-tech/erpnext_prime#20]
![WhatsApp Image 2020-01-29 at 3 59 47 PM](https://user-images.githubusercontent.com/26823124/73356768-0ea46e80-42c1-11ea-8606-1a017d4a4fe9.jpeg)

**Comment by nishantsoni4** [comment]
any update

**Comment by palashjhabak** [comment]
@nishantsoni4 Have updated this on live server. Please check and let me know. Closing the issue for now.
