### ISSUE TITLE
Sales Invoice Updation

### ISSUE THREAD

**Issue by nishantsoni4** [techlift-tech/erpnext_prime#4]
- Sales Invoice Edits : GST With HSN, Spacing Issue, Need GST Summary and Not HSN Summary (Urgent)

- POS format and wholesale format also

**Comment by nishantsoni4** [comment]
Need discount column in sales order "form"

**Comment by surajTechlift** [comment]
![Anita Provision - Daily Needs - GTO-2019-20-00907 11-16-2019 4-24-40 PM](https://user-images.githubusercontent.com/49982705/68992149-a206ff80-088d-11ea-8288-3b3fa04a84fd.png)
for discount

**Comment by nishantsoni4** [comment]
@surajTechlift any update with gst summary

**Comment by nishantsoni4** [comment]
ismey total gst % chahiye ek column and hsn summary nahi chahiye gst ka total summary chahiye 
and spacing ka kam karna hai

**Comment by palashjhabak** [comment]
@nishantsoni4 total GST as in ?

**Comment by nishantsoni4** [comment]
haan ek category ka total

**Comment by palashjhabak** [comment]
So neeche HSN wise tax hata ke, GST % wise table banana hai? 
e.g 
18% - 200
5% - 1000
etc. ?

**Comment by nishantsoni4** [comment]
exactly

**Comment by palashjhabak** [comment]
ok, Sales Invoice ka Print format pura redisgn karta hu
