### ISSUE TITLE
Notification

### ISSUE THREAD

**Issue by nishantsoni4** [techlift-tech/erpnext_prime#7]
SMS for Every Action (Payment, Receipt, Order Placed, Packed, Delivered) (Urgent)
Email Id Configuration to mail Vouchers to Desired party on the go

**Comment by nishantsoni4** [comment]
email is not working in erp

**Comment by nishantsoni4** [comment]
@palashjhabak

**Comment by surajTechlift** [comment]
@nishantsoni4  please mention the content of the sms so that should be added as content of sms

**Comment by nishantsoni4** [comment]
1- When Invoice Submitted
Dear Member,
Your PRIME <Order No.> has been packed. Vehicle and driver details to be shared shortly.
Pl. contact us on 8889234567 for any feedback

2-when Payment entry submitted
Dear Member,
Your Payment of Rs. 000000 has been Received as (MODE) against (INV NO)

Contact "PRIME" on 8889234567

Happy Selling


3- when sales order has submitted
Dear Member,
Your PRIME <Order No.> has been received.
Packing details to be shared shortly.
Pl. contact us on 8889234567 for any feedback

4-when delivery submitted
Dear Member,
Your PRIME <Order No.> has been Delivered by (Staff Name) and Rcvd by (rcvr name)
Pl. contact us on 8889234567 for any feedback

**Comment by nishantsoni4** [comment]
Nahi chahiye inko

**Comment by palashjhabak** [comment]
@nishantsoni4  kyu ?
