### ISSUE TITLE
Reports and documents requirement

### ISSUE THREAD

**Issue by nishantsoni4** [techlift-tech/erpnext_prime#8]
Item List (Item Name, MRP, Alias, HSN, IGST)
Customer List (Name, Group, Territory, Mobile, Email)
Supplier List (Name, Group, Territory, GSTIN)
Reports and its type
Lead Generation & Execution
Expiry Damage Loss Sampling Calculation
A-5 Print Profile for Payment & Journal Voucher (Urgent)

**Comment by nishantsoni4** [comment]
mrp is not showing in any item reports any update @surajTechlift

**Comment by palashjhabak** [comment]
@nishantshoni4 isme se kaun kaun sa point ho gaya hai, kaun sa pending hai and kaun sa not required hai, ek baar comment karke individual issues create kar de na please

Palash

**Comment by nishantsoni4** [comment]
A-5 Print Profile for Payment & Journal Voucher - sab hogaya hai but iska ka properly nahi dikha raha hai normal toh thik aata hai but invoice allocate kartey hai toh phir proper indentation nahi aata

**Comment by palashjhabak** [comment]
Ok theek hai check karta hu
