### ISSUE TITLE
loyalty program changes

### ISSUE THREAD

**Issue by nishantsoni4** [techlift-tech/erpnext_prime#9]
Cherish Loyalty Programme i'll update you for this

**Comment by palashjhabak** [comment]
@nishantsoni4 ye discuss hua kya fir? kaise karna hai isko

**Comment by nishantsoni4** [comment]
mey sir ko bata diya hu sir bole ki ek baar point to point  discuss karlo ek baar aur kya possible hai
@palashjhabak

**Comment by palashjhabak** [comment]
theek hai bata dena kab discuss karna hai, kar lenge koi issue nahi hai

**Comment by nishantsoni4** [comment]
2 baje tak call karta hu free rahoge

**Comment by palashjhabak** [comment]
haan 2 baje looks fine.
